/*
 * pwm_test.c
 * Created on: 2024-12-22
 * Author: Sebastien Cabana
 *
 * Description:
 * This program is designed to test and control a brushless motor for the BOAT robot 
 * using precise PWM signals generated by the Raspberry Pi. The motor follows a specific 
 * startup routine: providing power (5V), sending a 50 Hz PWM signal with a 5% duty cycle 
 * to initialize, and then controlling the speed by varying the duty cycle between 5% 
 * (stopped) and 10% (maximum speed).
 *
 * The program uses the WiringPi library to configure and control the PWM pins, leveraging 
 * its functions for clock settings, range adjustments, and PWM signal generation.
 * 
 * Usage:
 * 1. Compile the program using the following command:
 *    gcc -o pwm_test pwm_test.c -lwiringPi
 *
 * 2. Run the compiled program to begin listening for gamepad inputs:
 *    ./pwm_test
 *
 * Reference:
 * https://www.electronicwings.com/raspberry-pi/raspberry-pi-pwm-generation-using-python-and-c
 */

// Includes
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <wiringPi.h>

// Pin Definitions
#define MOTOR_PWM_PIN   26      // GPIO Pin for the motor PWM
#define POWER_GPIO_PIN  22      // GPIO Pin to provide 5V power to the motor

// PWM Constants
#define PWM_RANGE       1024    // Range for PWM (0-1023)
#define PWM_CLOCK_DIV   384     // Clock divisor for 50 Hz frequency (19.2 MHz / (384 * 1024) = 50 Hz)
#define DUTY_CYCLE_STOP 51      // 5% duty cycle (5% of 1024)
#define DUTY_CYCLE_MAX  102     // 10% duty cycle (10% of 1024)

// Function Prototypes
void PWM_Init();
void Motor_Startup();
void SetMotorSpeed(float speed); // Speed as a percentage (0.0 to 1.0)

int main() {
    // Initialize PWM
    PWM_Init();

    // Perform motor startup routine
    Motor_Startup();

    // Run example 3 times 
    for(int i = 0; i < 3; i++) {
        // Example: Test motor speed from 0% to 100%
        for (float speed = 0.0; speed <= 1.0; speed += 0.1) {
            SetMotorSpeed(speed);
            printf("Motor running at %.0f%% speed.\n", speed * 100);
            delay(1000); 
        }
    }

    // Stop the motor
    SetMotorSpeed(0.0);
    printf("Motor stopped.\n");
    delay(2000);
    return 0;
}

void PWM_Init() {
     // Initialize wiringPi
    if (wiringPiSetup() == -1) {
        fprintf(stderr, "Unable to start wiringPi: %s\n", strerror(errno));
        exit(1);
    }

    // Set PWM pin mode
    pinMode(MOTOR_PWM_PIN, PWM_OUTPUT);

    // Set GPIO pin for motor power
    pinMode(POWER_GPIO_PIN, OUTPUT);

    // Configure PWM clock and range for 50 Hz frequency
    pwmSetMode(PWM_MODE_MS);     // Use Mark:Space mode for stable frequency
    pwmSetClock(PWM_CLOCK_DIV); // Set clock divisor
    pwmSetRange(PWM_RANGE);     // Set range

    printf("PWM initialized for 50 Hz operation.\n");
}

void Motor_Startup() {
    // Provide power to the motor
    digitalWrite(POWER_GPIO_PIN, HIGH);
    printf("Motor power enabled via GPIO pin.\n");

    // Send a 5% duty cycle signal to initialize the motor
    pwmWrite(MOTOR_PWM_PIN, DUTY_CYCLE_STOP);
    printf("Motor startup signal sent (5%% duty cycle).\n");

    // Wait for motor initialization
    delay(1000);
}

void SetMotorSpeed(float speed) {
    if (speed < 0.0 || speed > 1.0) {
        fprintf(stderr, "Invalid speed value: %.2f. Valid range is 0.0 to 1.0.\n", speed);
        return;
    }

    // Calculate the PWM value based on the speed percentage
    int pwmValue = DUTY_CYCLE_STOP + (int)((DUTY_CYCLE_MAX - DUTY_CYCLE_STOP) * speed);

    // Reset motor if null speed to prevent motor getting stuck
    if(speed == 0.0) {
        digitalWrite(POWER_GPIO_PIN, LOW);
        delay(500);
        Motor_Startup();
    }

    // Write the PWM value to the motor pin
    else
        pwmWrite(MOTOR_PWM_PIN, pwmValue);

    printf("Motor speed set to %.0f%% (PWM value: %d).\n", speed * 100, pwmValue);
}
